### ISSUE TITLE
Support operations Like FieldName[2].key == SomeValue

### ISSUE THREAD

**Issue by NathanSpeidel** [bullet-db/bullet-core#47]
Currently values in a map can be accessed via
```
FieldName.key
```

Add support for accessing elements in a list as well:

```
FieldName[2].key
```

**Comment by akshaisarma** [comment]
I think we should use our existing syntax such as ```FieldName.0.key``` and when we access FieldName, we know its type (List or Map). If it's a List, then we use the next accessor as an index into the List, otherwise, we treat it as a String index into a Map.

**Comment by akshaisarma** [comment]
Addressed Filters and Aggregations with #68. Projections require more help from bullet-record
